import type { VoucherFormValues } from "./voucherSchema";

export const defaultVoucher: VoucherFormValues = {
  voucherType: "" as unknown as VoucherFormValues["voucherType"],
  tourType: "" as unknown as VoucherFormValues["tourType"],
  pageNumber: "1",
  date: new Date().toISOString().slice(0, 10),
  voucherTitle: "",
  hotelName: "",
  market: "",
  ratePeriod: "",
  requisitionNo: "REQ-0000",
  tourNo: "T/0000",
  tourName: "",
  customerName: "",
  confirmedBy: "",
  rateApplicable: 0,
  employeeName: "",
  employeeEmail: "",
  billingInstructions: "",
  remarks: "",
  matchedHotelRateId: undefined,
  rateApplicableText: "",
  guideText: "",
  surchargeText: "",
  eventSupplementText: "",
  manuallyEdited: false,
  lineItems: [
    {
      requiredDate: "",
      roomCategory: "",
      basis: "",
      singleRooms: 0,
      doubleRooms: 0,
      twinRooms: 0,
      tripleRooms: 0,
      child2_5: 0,
      child2_5Sharing: 0,
      child2_5Bed: 0,
      child2_5OwnRoom: 0,
      child6_11: 0,
      child6_11Sharing: 0,
      child6_11Bed: 0,
      child6_11OwnRoom: 0,
      guide: 0,
      guideBasis: "",
      arrivingFor: "",
      supplementary: [],
    },
  ],
};
